name = "lucri-cockpit-server"
main = "src/index.js"
compatibility_date = "2025-07-18"

[[d1_databases]]
binding = "DB"
database_name = "lucri-cockpit-db"
database_id = "1b4990a1-5bf2-4a1b-8503-c0da7411e673"

[vars]
APP_URL = "https://lucri-cockpit.pages.dev"
CONTA_AZUL_CLIENT_ID = "505p89h6j5qc34l6gdgadjtjau"
CONTA_AZUL_REDIRECT_URI = "https://lucri-cockpit-server.lucrifinancas-54e.workers.dev/api/contaazul/callback"
GOOGLE_CLIENT_ID = "639084962363-j00c9jsrvggglk02i358hhmqsqr48qgd.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://lucri-cockpit-server.lucrifinancas-54e.workers.dev/api/auth/google/callback"
